# Generated by Django 4.2.9 on 2026-03-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.CharField(blank=True, max_length=300)),
                ('responsavel', models.CharField(blank=True, max_length=200)),
                ('texto_recibo', models.TextField(blank=True, help_text='Texto adicional exibido no rodapé dos recibos')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dados da Empresa',
                'verbose_name_plural': 'Dados da Empresa',
            },
        ),
    ]
