# Generated by Django 4.2.9 on 2026-03-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelacomissao',
            name='status_contrato_banco',
            field=models.CharField(choices=[('ok', 'OK'), ('inadimplente', 'Inadimplente')], default='ok', max_length=20),
        ),
    ]
