# Generated by Django 4.2.9 on 2026-04-15 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comissoes", "0004_bonusmensalcoordenador"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parcelacomissao",
            options={
                "ordering": ["venda", "perfil_comissao", "numero_parcela"],
                "verbose_name": "Parcela de Comissão",
                "verbose_name_plural": "Parcelas de Comissão",
            },
        ),
    ]
