# Generated by Django 4.2.9 on 2026-03-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COBAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(choices=[('BBTS', 'BBTS'), ('ISF', 'ISF')], max_length=10, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'COBAN',
                'verbose_name_plural': 'COBANs',
            },
        ),
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField()),
                ('qtd_parcelas', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('coban', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consorcios', to='cadastros.coban')),
            ],
            options={
                'verbose_name': 'Consórcio',
                'verbose_name_plural': 'Consórcios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('imoveis', 'Bens Imóveis'), ('moveis', 'Bens Móveis'), ('outros', 'Outros Bens')], max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Bem',
                'verbose_name_plural': 'Tipos de Bem',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendedores', to='cadastros.coordenador')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FaixaComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_min', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_max', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percentuais', models.JSONField(help_text='Lista de percentuais por parcela. Ex: [0.5, 0.5, 0.5] para 3 parcelas')),
                ('ativo', models.BooleanField(default=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='cadastros.consorcio')),
            ],
            options={
                'verbose_name': 'Faixa de Comissão',
                'verbose_name_plural': 'Faixas de Comissão',
            },
        ),
        migrations.AddField(
            model_name='consorcio',
            name='tipo_bem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consorcios', to='cadastros.tipobem'),
        ),
        migrations.CreateModel(
            name='Assembleia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assembleia', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembleias', to='cadastros.consorcio')),
            ],
            options={
                'verbose_name': 'Assembleia',
                'verbose_name_plural': 'Assembleias',
                'ordering': ['-data_assembleia'],
            },
        ),
    ]
