# Generated by Django 4.2.9 on 2026-03-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('identidade', models.CharField(blank=True, max_length=30)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('orgao_emissor', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='Brasileiro(a)', max_length=50)),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2)),
                ('naturalidade', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('escolaridade', models.CharField(blank=True, choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior', 'Ensino Superior'), ('pos', 'Pós-Graduação')], max_length=20)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('renda', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('conta_bancaria', models.CharField(blank=True, max_length=20)),
                ('agencia', models.CharField(blank=True, max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
