# Generated by Django 4.2.9 on 2026-03-03 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField()),
                ('numero_contrato', models.CharField(max_length=50, unique=True)),
                ('valor_bem', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_total_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('coban', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='cadastros.coban')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='cadastros.consorcio')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_criadas', to=settings.AUTH_USER_MODEL)),
                ('tipo_bem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='cadastros.tipobem')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='cadastros.vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
    ]
