# Generated by Django 4.2.9 on 2026-03-06 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_cliente'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='cadastros.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('a_contemplar', 'A Contemplar'), ('contemplado', 'Contemplado'), ('cancelada', 'Cancelada')], default='a_contemplar', max_length=20),
        ),
    ]
